# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: ghcr.io
  repository: vidovgopol/kbot
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.3-c3605a8"
  os: linux
  arc: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
