apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: demo
    image: gcr.io/k8s-k3s-385714/demo:v1.0.0
    resources:
      limits:
        memory: "64M"
        cpu: "200m"
